./205componentjhoverun.sh
./210componentjhovepreproc.sh
./211componentdigitizationguidepreproc.sh
./220componentfoxmlcreate.sh
./230ingestcomponent.sh
./240addpidstocomponentmaster.sh
./250componentaddrelsext.sh
./251componentadddigitizationguide.sh
./252componentadddescmetadata.sh
./253componentaddcontent.sh
./260modifycomponentrelsext.sh
./261modifycomponentdigitizationguide.sh
./262modifycomponentdescmetadata.sh
./263modifycomponentcontent.sh
